version: '3.4'

services:
  
  logawebapp-service: # name used in loga-nginx.conf
    container_name: logawebapp-container
    image: hubua/logawebapp:20190225063937 # update tag with latest required
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  reverse-proxy-service:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./loga-nginx.conf:/etc/nginx/conf.d/default.conf