version: '3.3'

services:
  
  loga-service:
    container_name: loga-container
    image: hubua/loga_webui_core
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  reverse-proxy-service:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "4123:80" # [internal]:[external]
    volumes:
      - ./loga-nginx.conf:/etc/nginx/conf.d/default.conf