version: '3.3'

services:
  
  loga-service:
    container_name: loga-container
    image: hubua/loga_webapp:{TAG_HERE}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  reverse-proxy-service:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./loga-nginx.conf:/etc/nginx/conf.d/default.conf